# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4d8255fe344cf42e3648dd9abc05c71ae6a1e36f0eef932f3cfec0a5ee7e93a3d2343822c69699e28a30f9144ab7ed6595470fb472d48d720078bfd7df75dfb

test:
  secret_key_base: 75d9266838dbee75afc2ed864a7a5d3170ce5e8d2a5be4eaa695b5ddcf61eae9a81af50a996d03ee0e13d952a1716dc3c1c6d39541f5d4abcc1ba74bf6539880

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
